sudo: false
language: node_js
node_js:
- 12
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- yarn install
- yarn global add codecov
script:
- yarn lint
- yarn format
- yarn test
after_success:
  - codecov