name: Commands
on:
  issue_comment:
    types: [created]

# also make changes in ./on-label.yml
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: '${ORG}/${REPO}'
          path: ./actions
          ref: v27
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.${REPO}_ISSUE_TRIAGE_BOT_PAT}}
          config-path: commands
